### ISSUE TITLE
Can you share the link to paper?

### ISSUE THREAD

**Issue by shenbuguanni** [seorim0/SE-using-SRL-Model#1]

**Comment by seorim0** [comment]
Hello! Thank you for your interest in our research.

This paper has been submitted to ICASSP 2025. 
We do not plan to make the paper public until the results are announced.

**Comment by shenbuguanni** [comment]
please ask why use 0.2 as the compress factor, Is that an advantage over 0.3?

**Comment by seorim0** [comment]
I saw your question late because I didn't receive a notification. 
Sorry for the delayed response.

The compress factor was determined experimentally.
I tested values from 0.1 to 1, increasing by 0.1 each time, and in my case, 0.2 yielded the best performance.

However, this value seems to vary depending on the model.
Commonly used numbers appear to be 0.3, 0.5, and 0.7 (As far as I know).

**Comment by seorim0** [comment]
The paper link is now publicly available. 
You can check it at the following link.
https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=10888248

I hope this helps!

**Comment by shenbuguanni** [comment]
Thank you very much. I'll take the time to study it and come back to you if I have any questions.
